baseURL = "https://testing.kiwichat.eu.org/"
languageCode = "zh-cn"
title = "test blog"
theme = "github-style"

[params]
  author = "Testing"
  description = "😅"
  github = "app-oszkar"
  url = "https://test.kiwichat.eu.org/"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  avatar = "/images/oscar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

