baseURL = "https://oyyzz.github.io/"
languageCode = "zh-cn"
title = "oyyzz's blog"
theme = "github-style"

[params]
  author = "Wilson Edwards"
  description = "😅"
  github = "oyyzz"
  url = "https://oyyzz.github.io/"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  avatar = "/images/0.jpg"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

